#!/usr/bin/env python3
"""Render the canonical mascot placement rules into a book's CONTENT-GENERATION-GUIDE.md.

The rules live in exactly one place:

    book-installer/references/mascot-placement-rules.md

They must never be hand-copied into a book. This script substitutes the
book's character values into that file and splices the result between
sentinel comments, so the copy can be re-rendered whenever the canonical
rules change and can be checked for hand-edits with --check.

Usage:
    render-mascot-guide.py                 # render into ./CONTENT-GENERATION-GUIDE.md
    render-mascot-guide.py --check         # exit 1 if the guide has drifted
    render-mascot-guide.py --stdout        # print the rendered block only

Run from the project root (where mkdocs.yml lives). Character values are read
from docs/img/mascot/character-sheet.md and may be overridden with --set.

Exits 0 on success, 1 on drift (--check), 2 on usage or missing-file errors.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

BEGIN = "<!-- BEGIN mascot-placement-rules — generated by render-mascot-guide.py; do not edit by hand -->"
END = "<!-- END mascot-placement-rules -->"

# Marker left by the init-textbook base template showing where the mascot
# block belongs when it is inserted for the first time.
BASE_TEMPLATE_MARKER = re.compile(
    r"<!--\s*\n\s*No learning mascot has been added yet\..*?-->\s*\n",
    re.DOTALL,
)

DEFAULTS = {"TOPIC": "this topic"}

CHARACTER_SHEET_FIELDS = {
    "CHARACTER_NAME": "Name",
    "SPECIES": "Species",
    "SUBJECT": "Subject",
    "CATCHPHRASE": "Catchphrase",
}


def find_rules_file(explicit: str | None) -> Path:
    """Locate mascot-placement-rules.md without assuming any agent framework."""
    if explicit:
        return Path(explicit)
    # Alongside this script: scripts/ -> ../references/
    sibling = Path(__file__).resolve().parent.parent / "references" / "mascot-placement-rules.md"
    if sibling.is_file():
        return sibling
    import os

    bk_home = os.environ.get("BK_HOME")
    if bk_home:
        candidate = (
            Path(bk_home)
            / "skills"
            / "book-installer"
            / "references"
            / "mascot-placement-rules.md"
        )
        if candidate.is_file():
            return candidate
    return sibling  # report the expected path in the error


def read_character_sheet(path: Path) -> dict[str, str]:
    """Pull {{PLACEHOLDER}} values out of docs/img/mascot/character-sheet.md."""
    values: dict[str, str] = {}
    if not path.is_file():
        return values
    text = path.read_text(encoding="utf-8")
    for placeholder, label in CHARACTER_SHEET_FIELDS.items():
        m = re.search(
            rf"^\s*-\s*\*\*{re.escape(label)}:?\*\*:?\s*(.+?)\s*$",
            text,
            re.MULTILINE | re.IGNORECASE,
        )
        if m:
            value = m.group(1).strip().strip('"')
            # Character sheets often gloss a field, e.g.
            # "Sea otter (a young otter is called a *kit*)". The gloss belongs
            # in the character sheet, not in every heading that names the species.
            value = re.sub(r"\s*\(.*\)\s*$", "", value).strip()
            values[placeholder] = value
    return values


def strip_authoring_matter(text: str) -> str:
    """Remove frontmatter, the canonical-source notice, and the H1 title block."""
    # YAML frontmatter
    text = re.sub(r"\A---\n.*?\n---\n", "", text, flags=re.DOTALL)
    # The "CANONICAL SOURCE" HTML comment aimed at skill authors, not book readers
    text = re.sub(r"<!--\s*=+\s*\n.*?=+\s*-->\n", "", text, flags=re.DOTALL)
    # The H1 and the placeholder-substitution note (meta, not content)
    text = re.sub(r"\A\s*#\s+Mascot Placement Rules\n", "", text)
    text = re.sub(
        r"\nPlaceholders \(`\{\{CHARACTER_NAME\}\}`.*?CONTENT-GENERATION-GUIDE\.md`\.\n",
        "",
        text,
        flags=re.DOTALL,
    )
    return text.strip() + "\n"


def demote_headings(text: str) -> str:
    """Shift every ATX heading one level deeper so the block nests under an H2."""
    out = []
    in_fence = False
    for line in text.split("\n"):
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
        if not in_fence and re.match(r"^#{1,5} ", line):
            line = "#" + line
        out.append(line)
    return "\n".join(out)


def render(rules_path: Path, values: dict[str, str]) -> str:
    text = rules_path.read_text(encoding="utf-8")
    text = strip_authoring_matter(text)
    text = demote_headings(text)

    missing = sorted(
        set(re.findall(r"\{\{([A-Z_]+)\}\}", text)) - set(values)
    )
    if missing:
        print(
            "Warning: no value supplied for: " + ", ".join(missing),
            file=sys.stderr,
        )
    for key, value in values.items():
        text = text.replace("{{" + key + "}}", value)

    return f"{BEGIN}\n\n{text}\n{END}\n"


def section_header(values: dict[str, str]) -> str:
    name = values.get("CHARACTER_NAME", "{{CHARACTER_NAME}}")
    species = values.get("SPECIES", "{{SPECIES}}")
    return f"## Learning Mascot: {name} the {species}\n"


def splice(guide_text: str, block: str, header: str) -> str:
    """Replace the sentinel block in place, or create the section if absent.

    Only the text between the sentinels is regenerated. The section heading and
    any book-specific subsections above the sentinels (Mascot File Index,
    Character Overview, Voice Characteristics) are authored per book and are
    preserved across re-renders.
    """
    if BEGIN in guide_text and END in guide_text:
        start = guide_text.index(BEGIN)
        stop = guide_text.index(END) + len(END) + 1
        return guide_text[:start] + block + guide_text[stop:]

    new_section = header + "\n" + block + "\n"

    m = BASE_TEMPLATE_MARKER.search(guide_text)
    if m:
        return guide_text[: m.start()] + new_section + guide_text[m.end() :]

    # Fall back to inserting before the first level-2 heading.
    m = re.search(r"^## ", guide_text, re.MULTILINE)
    if m:
        return guide_text[: m.start()] + new_section + guide_text[m.start() :]

    return guide_text.rstrip() + "\n\n" + new_section


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--guide", default="CONTENT-GENERATION-GUIDE.md")
    ap.add_argument("--rules", default=None)
    ap.add_argument("--character-sheet", default="docs/img/mascot/character-sheet.md")
    ap.add_argument(
        "--set",
        action="append",
        default=[],
        metavar="KEY=VALUE",
        help="Override a placeholder, e.g. --set CHARACTER_NAME=Kit",
    )
    ap.add_argument("--check", action="store_true", help="exit 1 if the guide has drifted")
    ap.add_argument("--stdout", action="store_true", help="print the block, do not write")
    args = ap.parse_args()

    rules_path = find_rules_file(args.rules)
    if not rules_path.is_file():
        print(f"Error: canonical rules not found at {rules_path}", file=sys.stderr)
        return 2

    values = dict(DEFAULTS)
    values.update(read_character_sheet(Path(args.character_sheet)))
    for pair in args.set:
        if "=" not in pair:
            print(f"Error: --set expects KEY=VALUE, got {pair!r}", file=sys.stderr)
            return 2
        key, value = pair.split("=", 1)
        values[key.strip()] = value.strip()

    block = render(rules_path, values)

    if args.stdout:
        sys.stdout.write(block)
        return 0

    guide = Path(args.guide)
    if not guide.is_file():
        print(f"Error: guide not found at {guide}", file=sys.stderr)
        return 2

    original = guide.read_text(encoding="utf-8")
    updated = splice(original, block, section_header(values))

    if args.check:
        if original == updated:
            print(f"OK — {guide} matches the canonical mascot placement rules.")
            return 0
        print(
            f"DRIFT — {guide} does not match the canonical rules at {rules_path}.\n"
            f"Re-render with: {Path(__file__).name}",
            file=sys.stderr,
        )
        return 1

    if original == updated:
        print(f"OK — {guide} already up to date.")
        return 0

    guide.write_text(updated, encoding="utf-8")
    print(f"Rendered mascot placement rules into {guide}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
